# Assignment Day 4 | 9th July 2020

### __Question-1__ Create a 3x3x3 array with random values

In [61]:
import numpy as np #import numpy library
#program to create a 3x3x3 array with random values
arr = np.random.random((3,3,3)) #creating 3x3x3 array using random function
print(arr) #printing the array

[[[0.93068282 0.56700522 0.24265174]
  [0.35306087 0.31099502 0.57820169]
  [0.03823979 0.40651805 0.15481966]]

 [[0.71048845 0.76726831 0.33058035]
  [0.05374502 0.20210811 0.02497793]
  [0.05649288 0.38758992 0.27180765]]

 [[0.4932047  0.90380398 0.42675775]
  [0.76682242 0.73674103 0.35581069]
  [0.9004335  0.5194338  0.40096727]]]


### __Question-2__ Create a 5x5 matrix with values 1,2,3,4,5 just below the diagonal

In [62]:
#program to create a 5x5 matrix with values 1,2,3,4,5 just below the diagonal
arr = np.diag([1,2,3,4,5]) #creating matrix with given diagonal
print(arr) #priting the matrix

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Question-3 Create a 8x8 matrix and fill it with a checkerboard pattern

In [64]:
#program to create a 8x8 matrix and fill it with a checkerboard pattern
arr = np.zeros((8,8),dtype=int) #creating the 8x8 array with zeros
arr[1::2,::2] = 1 #replacing zero with 1 from 1st,3rd,5th and 7th row with space of 2
arr[::2,1::2] = 1 #replacing zero with 1 from 0th,2nd,4th and 6th row with starting space of 2
print(arr) #printing the matrix

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Question-4 Normalize a 5x5 random matrix

In [73]:
#program to normalize a 5x5 random matrix
arr = np.random.random((5,5))#creating matrix using random function
print("Original Matrix:\n",arr) #printig the original matorix 
arrmin, arrmax = arr.min(),arr.max() #finding the min and max
arr = (arr-arrmin)/(arrmax-arrmin) #operation to make matrix normalized
print("\nAfter Normlize:\n",arr) #printing the normlize matrix

Original Matrix:
 [[0.88692339 0.68646105 0.82172156 0.60581965 0.30695246]
 [0.9612937  0.76229028 0.71976604 0.93027382 0.718546  ]
 [0.39609424 0.72874016 0.97995226 0.14416159 0.47117765]
 [0.27561274 0.58539265 0.38450642 0.01051692 0.15131719]
 [0.92632608 0.45611235 0.45680476 0.03474634 0.84437737]]

After Normlize:
 [[0.90403809 0.69725551 0.83678055 0.61407162 0.30578165]
 [0.98075317 0.77547551 0.73161055 0.94875529 0.73035204]
 [0.39773392 0.7408676  1.         0.13785826 0.47518459]
 [0.27345385 0.59300059 0.38578076 0.         0.14523947]
 [0.94468308 0.45964431 0.46035855 0.02499333 0.86015067]]


### Question-5 How to find common values between two arrays?

In [74]:
#program to find common values between two arrays
arr1 = np.array([10,30,50,60,70]) #creating an array
arr2 = np.array([10,50,70]) #areating an array
print("Original Array 1:\n",arr1) #printing the array
print("\nOriginal Array 2:\n",arr2) #printing the array2
arr3 = np.intersect1d(arr1,arr2) #finding the common value using intersect
print("\nCommon Values:\n",arr3) #printing the array woth comoon values

Original Array 1:
 [10 30 50 60 70]

Original Array 2:
 [10 50 70]

Common Values:
 [10 50 70]


### Question-6 How to get the dates of yesterday, today and tomorrow?

In [75]:
yesterday = np.datetime64('today') - 1 #get yesterday date using datetime64 function
print("Yestraday: ",yesterday) #printing yesterday's date
today     = np.datetime64('today') #get today daye using datetime64 function
print("Today: ",today) #printing today's date
tomorrow  = np.datetime64('today') + 1 #get tomorrow's date using datetime64 function
print("Tomorrow: ",tomorrow) #printing tomorrow's date

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


### Question-7 Consider two random array A and B, check if they are equal

In [76]:
arr = np.random.random((3,3)) #creating random array
arr2 = np.random.random((3,3)) #creating random array 
result = np.allclose(arr,arr2) #comparing the two random arrays using allclose method
print("Both arrays are equal or not:",result) #printing the reslt after comparision

Both arrays are equal or not: False


### Question-8 Create random vector of size 10 and replace the maximum value by 0

In [58]:
arr = np.random.random(10) #creating random vector size 10
print("Original Array:") 
print(arr,"\n") #printing the original array
arr[arr.argmax()] = 0 #replacing the maximum value by 0
print("After maximum value changed by 0")
print(arr) #printing the array after changing the value

Original Array:
[0.8258998  0.49962685 0.21991589 0.49281146 0.0720348  0.66227321
 0.67886303 0.02269101 0.57446245 0.26247225] 

After maximum value changed by 0
[0.         0.49962685 0.21991589 0.49281146 0.0720348  0.66227321
 0.67886303 0.02269101 0.57446245 0.26247225]


### Question-9 How to print all the values of an array?

In [77]:
arr = np.random.random((3,3)) #creating the random array
print("All the values of an Array:\n",arr) #printing all the values of array

All the values of an Array:
 [[0.54825685 0.94192268 0.32456434]
 [0.24420498 0.02707245 0.52616353]
 [0.33083088 0.89239435 0.02139   ]]


### Question-10 Subtract the mean of each row of a matrix

In [80]:
print("Original matrix:")
arr = np.random.rand(3,3) #creating random matrix
print(arr) #printing the original matrix
print("\nSubtract the mean of each row of matrix:") #
arr1 = arr - arr.mean() #subtracting mean value with original value
print(arr1) #printing the array after opration

Original matrix:
[[0.53091037 0.29847875 0.07117223]
 [0.46287093 0.48758332 0.92847188]
 [0.92170552 0.74041655 0.78766973]]

Subtract the mean of each row of matrix:
[[-0.05012066 -0.28255228 -0.5098588 ]
 [-0.1181601  -0.09344772  0.34744085]
 [ 0.34067449  0.15938552  0.20663869]]


### Question-11 Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [81]:
arr = np.array([1,2,3,4]) + np.array([1,2,3,4]) #adding the two vector
print(arr) #priting the result after adding

[2 4 6 8]


### Question-12 How to get the diagonal of a dot product?

In [83]:
arr = np.array([[1,2],[3,4]])  #creating the 2-D array
print("Original Array1:\n",arr) #printing the array
arr1 = np.array([[11,12],[13,14]]) #creating the 2-D array
print("\nOriginal Array2:\n",b) #printng the array
dotab = np.dot(a,b) #applying dot on the two matrix
print("\nArray after dot opertaion:\n",x) #prinitng result after dot operation 
print("\nDiagnoal of the dot array of Array1 and Array2:\n",np.diagonal(dotab)) #printing the diagonal of dot matrix

Original Array1:
 [[1 2]
 [3 4]]

Original Array2:
 [[11 12]
 [13 14]]

Array after dot opertaion:
 5

Diagnoal of the dot array of Array1 and Array2:
 [37 92]


### Question-13 How to find the most frequent value in an array?

In [86]:
arr = np.random.randint(0,10,6) #creating random array
print("Original Array:\n",arr) #printing the original array
mostfrq = np.bincount(arr).argmax() #getting the most frequent value for the array
print(mostfrq) #printing the most frequent value of the array

Original Array:
 [1 5 0 7 0 2]
0


### Question-14 How to get the n largest values of an array

In [88]:
arr = np.random.randint(0,10,size=(3,3)) #creating the random array
print("Original Array:\n",arr) #printing the original array
print(arr.max()) #prinitng the max value out of it

Original Array:
 [[7 0 8]
 [2 1 7]
 [6 3 8]]
8


### Question-15 How to create a record array from a regular array?

In [98]:
arra1 = np.array([("Vaibhav Patel", 88.5, 90),
                 ("Pankil Desai", 87, 99),
             ("Rachit Jain", 85.5, 91)]) #creating regular array
print("Original array:\n",arra1) # printing the original array 

print("\nRecord array:")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8') #creating the record array
print(result) #priting the result

Original array:
 [['Vaibhav Patel' '88.5' '90']
 ['Pankil Desai' '87' '99']
 ['Rachit Jain' '85.5' '91']]

Record array:
[(b'Vaibhav Patel', 88.5, 90) (b'Pankil Desai', 87. , 99)
 (b'Rachit Jain', 85.5, 91)]
